### ISSUE TITLE
Error when handling large docs

### ISSUE THREAD

**Issue by Jotschi** [joaompinto/asciidoctor-vscode#17]
I have rather large adoc which can be processed because the output of the asciidoctor program exceeds some buffer value:

> 
> Error
> 
> stdout maxBuffer exceeded Error: stdout maxBuffer exceeded at Socket. (child_process.js:271:14) at emitOne (events.js:96:13) at Socket.emit (events.js:188:7) at readableAddChunk (_stream_readable.js:176:18) at Socket.Readable.push (_stream_readable.js:134:10) at Pipe.onread (net.js:543:20) 
>

**Comment by Jotschi** [comment]
I just bumped the `maxBuffer` size to fix this for me. But I guess it would be better to read the buffer until all content has been retrieved.

```ts
diff --git a/src/AsciiDocProvider.ts b/src/AsciiDocProvider.ts
index 061f60f..d3c322f 100644
--- a/src/AsciiDocProvider.ts
+++ b/src/AsciiDocProvider.ts
@@ -16,6 +16,7 @@ import {
 } from 'vscode';
 
 import { exec } from "child_process";
+import { ExecOptionsWithBufferEncoding } from "child_process";
 import * as fs from "fs";
 import * as path from "path";
 let fileUrl = require("file-url");
@@ -114,7 +115,11 @@ export default class AsciiDocProvider implements TextDocumentContentProvider {
             let html_gerenator = workspace.getConfiguration('AsciiDoc').get('html_generator')
             let cmd = `${html_gerenator} "${tmpobj.name}"`
             fs.write(tmpobj.fd, text, 0);
-            exec(cmd, (error: Error, stdout: Buffer, stderr: Buffer) => {
+            let options : ExecOptionsWithBufferEncoding = {
+                encoding: null,
+                maxBuffer: 1024*500
+            };
+            exec(cmd, options, (error: Error, stdout: Buffer, stderr: Buffer) => {
                 tmpobj.removeCallback();
                 if (error) {
                     let errorMessage = [
```

**Comment by diiigle** [comment]
+1

**Comment by joaompinto** [comment]
Added this patch to 0.3.5 release right now. Thanks for the fix.
