### ISSUE TITLE
Problems installing the plugin

### ISSUE THREAD

**Issue by ChristianZip** [joaompinto/asciidoctor-vscode#49]
Hi all,
I have a problem installing the asciidoctor plugin in vscode on my mac.

Im using:

- macOS Sierra 10.12.6
- vscode 1.21

When installing the plugin  with the installer the installation seems to run fine. I can see the commands of the plugin:

![image](https://user-images.githubusercontent.com/37420439/37489567-632cae44-2898-11e8-997b-88dd756d45a3.png)

But when I select one of those commands I receive the following error messages:

![image](https://user-images.githubusercontent.com/37420439/37489593-7b97a704-2898-11e8-94a4-62d95f00066b.png)
or
![image](https://user-images.githubusercontent.com/37420439/37489627-8e56d46e-2898-11e8-8612-1a1fa429560e.png)

Therefore I removed the plugin and executed the installation like described in the marketplace:

> git clone https://github.com/joaompinto/asciidoctor-vscode
> cd asciidoctor-vscode
> npm install
> sudo npm install -g vsce typescript
> vsce package
> code --install-extension *.vsix

When executing:
> vsce package
I receive another error message:

```
Executing prepublish script 'npm run vscode:prepublish'...
Error: Command failed: npm run vscode:prepublish
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! asciidoctor-vscode@0.3.8 vscode:prepublish: `tsc -p ./`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the asciidoctor-vscode@0.3.8 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2018-03-15T20_37_31_295Z-debug.log
```

And in this log I can find the following information:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/9.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'vscode:prepublish' ]
2 info using npm@5.6.0
3 info using node@v9.8.0
4 verbose run-script [ 'prevscode:prepublish',
4 verbose run-script   'vscode:prepublish',
4 verbose run-script   'postvscode:prepublish' ]
5 info lifecycle asciidoctor-vscode@0.3.8~prevscode:prepublish: asciidoctor-vscode@0.3.8
6 info lifecycle asciidoctor-vscode@0.3.8~vscode:prepublish: asciidoctor-vscode@0.3.8
7 verbose lifecycle asciidoctor-vscode@0.3.8~vscode:prepublish: unsafe-perm in lifecycle true
8 verbose lifecycle asciidoctor-vscode@0.3.8~vscode:prepublish: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/.../programs/asciidoctor-vscode/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/.../arcanist/arcanist/bin/
9 verbose lifecycle asciidoctor-vscode@0.3.8~vscode:prepublish: CWD: /Users/.../programs/asciidoctor-vscode
10 silly lifecycle asciidoctor-vscode@0.3.8~vscode:prepublish: Args: [ '-c', 'tsc -p ./' ]
11 silly lifecycle asciidoctor-vscode@0.3.8~vscode:prepublish: Returned: code: 2  signal: null
12 info lifecycle asciidoctor-vscode@0.3.8~vscode:prepublish: Failed to exec vscode:prepublish script
13 verbose stack Error: asciidoctor-vscode@0.3.8 vscode:prepublish: `tsc -p ./`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid asciidoctor-vscode@0.3.8
15 verbose cwd /Users/.../programs/asciidoctor-vscode
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/Cellar/node/9.8.0/bin/node" "/usr/local/bin/npm" "run" "vscode:prepublish"
18 verbose node v9.8.0
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error asciidoctor-vscode@0.3.8 vscode:prepublish: `tsc -p ./`
22 error Exit status 2
23 error Failed at the asciidoctor-vscode@0.3.8 vscode:prepublish script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

Do you have any Idea why the installation of your plugin does  not work for  me?
Thank you!
regards
Christian

**Comment by joaompinto** [comment]
Hello,
could you please test with the latest VSCode and extension versions ?

Thanks

**Comment by joaompinto** [comment]
Please reopen if neefed.
