### ISSUE TITLE
command 'adoc.preview' not found

### ISSUE THREAD

**Issue by weijiahan** [joaompinto/asciidoctor-vscode#88]
I can not preview asciidoc when I installed the [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) extension. 

The following error happens:

`command 'adoc.preview' not found`
or
`command 'adoc.previewToSide' not found`

**Comment by GoGoris** [comment]
I am having the same problem, I get the following stacktrace when both extensions are installed: 

```
ReferenceError: Opal is not defined
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\node_modules\opal-runtime\src\opal.js:2316:1)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\node_modules\opal-runtime\src\opal.js:22183:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\node_modules\opal-runtime\src\index.js:2:1)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\node_modules\opal-runtime\src\index.js:13:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\node_modules\asciidoctor.js\dist\node\asciidoctor.js:2:14)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\node_modules\asciidoctor.js\dist\node\asciidoctor.js:18510:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\out\src\text-parser.js:13:21)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\out\src\text-parser.js:127:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\out\src\TextDocumentContentProvider.js:12:21)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\out\src\TextDocumentContentProvider.js:95:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\out\src\extension.js:15:39)
	at Object.<anonymous> (%USERPROFILE%\.vscode\extensions\joaompinto.asciidoctor-vscode-0.12.0\out\src\extension.js:84:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Function.i [as __$__nodeRequire] (c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js:30:770)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:131
	at t._doActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:721:243)
	at t._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:720:161)
	at Object.actualActivateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:718:48)
	at e._activateExtension (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:428:188)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:427:757
	at Array.map (native)
	at e._activateExtensions (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:427:732)
	at e.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:426:14)
	at t.activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:718:412)
	at t.$activateByEvent (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:722:827)
	at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:737)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:599:455)
	at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:529)
	at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:598:298)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:597:226
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:600:324
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:119
	at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:496)
	at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:145:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
```

**Comment by joaompinto** [comment]
I am unable to reproduce the problem in Linux, I will try later today on Windows.

**Comment by joaompinto** [comment]
I was not able to reproduce the problem with both extensions in my windows system, from the backstrace it seems that something is messing with the Opal node module which is installed as a dependency for asciidoctor.js .

**Comment by ralfbiedert** [comment]
Same here on relatively fresh macOS installation. 

![screen shot 2018-06-12 at 15 34 07](https://user-images.githubusercontent.com/301288/41293611-10fb72be-6e56-11e8-88a2-bf06d9c46bbd.png)

**Comment by eskild** [comment]
Same as @ralfbiedert here on macOS after upgrade to VSCode 1.24.0 (May).

**Comment by snewman** [comment]
Ditto - just started happening this week. Not installed any new extensions, preview was working fine a week ago, and it's just stopped working. I'm seeing "command 'adoc.previewToSide' not found when trying to open the preview pane.

AsciiDoc 0.15.0
Visual Code 1.26.1
OS: MacOS 10.13.6

Other extensions:
Code Spell Checker 1.6.10
Python 2018.7.1
Todo Tree 0.0.78.

Going to try removing and re-installing and see if that fixes it.

**Comment by joaompinto** [comment]
Extension does not work after the vscode upgrade to 1.26.1 .

**Comment by joaompinto** [comment]
The issue is random, after restart I am unable to reproduce the problem.

**Comment by wireless00** [comment]
I have the same issue today as of version  1.34.0 (1.34.0). I did not had the issue at the previous version

**Comment by ochaloup** [comment]
I have the same issue with version 1.34.0 on Fedora 28.

**Comment by leehambley** [comment]
also with 

```
$ code --version
2019/06/12 18:26:30.961968 cmd_run.go:375: restoring default SELinux context of /home/lhambley/snap
1.35.0
553cfb2c2205db5f15f3ee8395bbd5cf066d357d
x64
```
on `Fedora release 30 (Thirty)`

**Comment by SiarheiBobryk** [comment]
After updating to 1.35

`command 'asciidoc.showPreviewToSide' not found`

```
$ code --version
1.35.1
c7d83e57cd18f18026a8162d042843bda1bcf21f
x64
```

**Comment by joaompinto** [comment]
This does not seem related to the original issue (despite the same error message), following up this new event on https://github.com/asciidoctor/asciidoctor-vscode/issues/88 .
